### ISSUE TITLE
LSCOLORS for MacOS ls

### ISSUE THREAD

**Issue by logic** [seebi/dircolors-solarized#10]
I wasn't quite sure where to post this, so figured an issue off of your repository might be the most likely to be found by others. :) I took a bit of time today and roughly mirrored the base colors that your solarized theme for dircolors gives in OSX's LSCOLORS environment variable:

``` bash
export LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD
```

It's not nearly as comprehensive (you can't do file-type matching, for example), but it should be close, for those who don't want to replace ls with the GNU version.

**Comment by zevav** [comment]
@teoljungberg is "aliases" meant to be a directory or file (8.23_1 has no such file/directory)?  what should be done after adding these lines to .bashrc/.bash_profile to make this work?

**Comment by teoljungberg** [comment]
@zevav It was when I wrote up that guideline, but after looking into it now I can see that it's not a directory.  If you use homebrew as I used, and if you have `/usr/local/bin` in your path you have all of these in your `PATH` already. You can just alias `ls` to `gls`

**Comment by lukebpowell** [comment]
If you install GNU coreutils with homebrew, the ``eval `dircolors /path/to/dircolorsdb` `` command from the documentation will need to be changed to ``eval `gdircolors /path/to/dircolorsdb` ``.

**Comment by antoineco** [comment]
I used http://misc.twam.info/lscolors/ to generate my `LSCOLORS` variable. The result for `dircolors.ansi-dark` is `LSCOLORS="exfxfexeBxdehehbhdacex"`. There is no major difference besides directories which are blue instead of cyan. 

Because the original screenshots disappeared I made some myself:

**Comparison**

With the OP's value:

![op](https://user-images.githubusercontent.com/3299086/38802146-fc76bfcc-416b-11e8-8b08-85fe3ebe14b0.png)

With the generated value:

![generated](https://user-images.githubusercontent.com/3299086/38802154-005d905c-416c-11e8-8aec-fb149222c3aa.png)

On Linux:

![linux](https://user-images.githubusercontent.com/3299086/38802422-acac71a2-416c-11e8-95e9-1b2ee2633917.png)

**Comment by levelont** [comment]
This worked for me:

https://apple.stackexchange.com/questions/282185/how-do-i-get-different-colors-for-directories-etc-in-iterm2

**Comment by jspv** [comment]
Any chance there is a more recent LSCOLORS example that matches the ones in this repository?  For example, the symbolic link in this repo's discolors example is cyan (light blue), the LSCOLORS in this thread and screenshots show it as magenta (bright purple).
